services:
  - docker

script:
  - bundle exec jekyll build 2>&1 | tee output.log
  - grep -i "error" output.log > /dev/null ; test $? -ne 0 # fail if there is an error in output.log
  - echo "pip3 install PyYAML==3.12 && python3 check_events.py" > check_events.sh ; docker run --rm -it -v $(pwd):/opt/code:ro --workdir=/opt/code --name codefor.de python:3.6 bash check_events.sh

branches:
  only:
    - gh-pages
    - /.*/
