markdown: kramdown
exclude: ["vendor"]
permalink: /:categories/:title
excerpt_separator: "\n"
paginate: 5
paginate_path: "blog/:num"
collections:
  projekte:
    output: true
    permalink: /projekte/:path/