markdown: kramdown
exclude: ["vendor"]
permalink: /:categories/:title
excerpt_separator: "\n\n"
paginate: 5
paginate_path: "news/:num"
collections:
  projekte:
    output: true
    permalink: /projekte/:path/